name: CoinCard
version: 1.5
main: com.foxsrv.coincard.CoinCardPlugin
api-version: "1.20"
depend: [Vault]
softdepend: [PlaceholderAPI]
author: FoxSRV
commands:
  coin:
    description: Main Command
    usage: /coin <subcommand>
permissions:
  coin.admin:
    description: Permission for adm commands
    default: op
